In [5]:
#Import Library
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [7]:
#Read Dataset
df = pd.read_csv('https://github.com/YBIFoundation/ProjectDataSet/raw/main/Fresher%20Hiring%20Selection.csv')

In [8]:
#Display Dataset Shape
df

      Unnamed: 0  Age  CGPA  ...  Hackathon_Participation  Attendance  Selected
0              0   24    65  ...                        0          88         1
1              1   21    75  ...                        5          96         0
2              2   25    80  ...                        0          91         1
3              3   22    58  ...                        5          84         1
4              4   24    88  ...                        3          69         1
...          ...  ...   ...  ...                      ...         ...       ...
1995        1995   19    67  ...                        4          97         1
1996        1996   22    65  ...                        4          92         1
1997        1997   21    70  ...                        2          77         1
1998        1998   18    62  ...                        3          82         1
1999        1999   20    94  ...                        5          62         1

[2000 rows x 13 columns]

In [9]:
#Display first 10 records
df.head(10)

   Unnamed: 0  Age  CGPA  ...  Hackathon_Participation  Attendance  Selected
0           0   24    65  ...                        0          88         1
1           1   21    75  ...                        5          96         0
2           2   25    80  ...                        0          91         1
3           3   22    58  ...                        5          84         1
4           4   24    88  ...                        3          69         1
5           5   20    72  ...                        3          94         1
6           6   24    94  ...                        4          84         1
7           7   25    89  ...                        5          86         1
8           8   22    95  ...                        3          91         0
9           9   21    83  ...                        5          71         1

[10 rows x 13 columns]

In [10]:
#Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               2000 non-null   int64
 1   Age                      2000 non-null   int64
 2   CGPA                     2000 non-null   int64
 3   Aptitude_Score           2000 non-null   int64
 4   Programming_Score        2000 non-null   int64
 5   SQL_Score                2000 non-null   int64
 6   Communication_Score      2000 non-null   int64
 7   Projects                 2000 non-null   int64
 8   Certifications           2000 non-null   int64
 9   Internship_Months        2000 non-null   int64
 10  Hackathon_Participation  2000 non-null   int64
 11  Attendance               2000 non-null   int64
 12  Selected                 2000 non-null   int64
dtypes: int64(13)
memory usage: 203.3 KB

In [11]:
#Check missing values
df.isnull().sum()

Unnamed: 0                 0
Age                        0
CGPA                       0
Aptitude_Score             0
Programming_Score          0
SQL_Score                  0
Communication_Score        0
Projects                   0
Certifications             0
Internship_Months          0
Hackathon_Participation    0
Attendance                 0
Selected                   0
dtype: int64

In [12]:
#Generate summary statistics.
df.describe()

        Unnamed: 0         Age  ...   Attendance    Selected
count  2000.000000  2000.00000  ...  2000.000000  2000.00000
mean    999.500000    21.92650  ...    80.201000     0.88750
std     577.494589     2.59142  ...    11.891775     0.31606
min       0.000000    18.00000  ...    60.000000     0.00000
25%     499.750000    20.00000  ...    70.000000     1.00000
50%     999.500000    22.00000  ...    80.000000     1.00000
75%    1499.250000    24.00000  ...    91.000000     1.00000
max    1999.000000    26.00000  ...   100.000000     1.00000

[8 rows x 13 columns]

In [13]:
#Find percentage of selected candidates
Selected_percentage = (df['Selected'].mean()) *100
print('Selected Percentage',round(Selected_percentage,2),'%')

Selected Percentage 88.75 %

In [14]:
df.columns

Index(['Unnamed: 0', 'Age', 'CGPA', 'Aptitude_Score', 'Programming_Score',
       'SQL_Score', 'Communication_Score', 'Projects', 'Certifications',
       'Internship_Months', 'Hackathon_Participation', 'Attendance',
       'Selected'],
      dtype='object')

In [15]:
#Define x and y
y=df['Selected']
x=df[['Age', 'CGPA', 'Aptitude_Score', 'Programming_Score',
       'SQL_Score', 'Communication_Score', 'Projects', 'Certifications',
       'Internship_Months', 'Hackathon_Participation', 'Attendance']]

In [16]:
x.shape, y.shape

((2000, 11), (2000,))

In [17]:
#Train Test Split
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=2)

In [19]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1500, 11), (500, 11), (1500,), (500,))

In [20]:
#Select Model (Logistic Regression)
from sklearn.linear_model import LogisticRegression

In [21]:
model = LogisticRegression()

In [1]:
#Train Model
model.fit(x_train,y_train)

NameError: name 'model' is not defined

In [23]:
#Prediction
y_pred = model.predict(x_test)

In [24]:
#Evaluation
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.82      0.57      0.67        54
           1       0.95      0.98      0.97       446

    accuracy                           0.94       500
   macro avg       0.88      0.78      0.82       500
weighted avg       0.94      0.94      0.94       500